# Generated by Django 4.2.4 on 2023-10-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pra_admin', '0010_allocation_record_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pratical_marks', models.IntegerField(null=True)),
                ('viva_marks', models.IntegerField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pra_admin.examschedule')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pra_admin.student')),
            ],
            options={
                'db_table': 'User_Marksheet',
            },
        ),
    ]
