# Generated by Django 4.2.4 on 2023-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pra_admin', '0003_examiner_semester_subject_remove_student_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
