# Generated by Django 4.2.4 on 2023-09-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pra_admin', '0006_alter_examschedule_date_alter_examschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examschedule',
            table='Ad_ExamSchedule',
        ),
        migrations.AlterModelTable(
            name='lab',
            table='Ad_lab',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Ad_subject',
        ),
    ]
