# Generated by Django 4.2.4 on 2023-10-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pra_admin', '0007_alter_examschedule_table_alter_lab_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=200, null=True)),
                ('batch_size', models.IntegerField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pra_admin.examschedule')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pra_admin.examiner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pra_admin.student')),
            ],
            options={
                'db_table': 'Ad_Allocation',
            },
        ),
    ]
