# Generated by Django 4.2.4 on 2023-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pra_admin', '0010_allocation_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_record',
            name='batch_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
