# Generated by Django 4.2.4 on 2023-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pra_admin', '0012_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_record',
            name='batch_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
